language: php

matrix:
  fast_finish: true
  include:
    - os: windows
      language: sh
      before_install:
        - choco install php --version 7.4
        - choco install composer
        - export PATH="/c/tools/php74:/c/ProgramData/ComposerSetup/bin/:/c/ProgramData/chocolatey/lib/ffmpeg/tools:$PATH"
    - php: '7.1'
      install:
        - composer update --no-interaction
    - php: '7.2'
      install:
        - composer update --no-interaction
    - php: '7.3'
    - php: '7.4'
    - php: 'nightly'
      install:
        - composer install --no-interaction --ignore-platform-reqs --no-cache
    - php: '7.4'
      name: 'Prefer lowest'
      install:
        - composer update --prefer-lowest
  allow_failures:
    - php: 'nightly'

env:
  global:
    - XDEBUG_MODE=coverage

cache:
  directories:
    - $HOME/.cache/composer/files

install:
  composer install --no-interaction

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit

after_script:
 - bash <(curl -s https://codecov.io/bash)